### ISSUE TITLE
has_whiff_of_total function removal 

### ISSUE THREAD

**Issue by banillie** [hammerheadlemon/bcompiler#3]
Hi Matt, you might remember that around three months ago (last commission time, so we're back to that point once again!) I queried whether bcompiler -a (master to templates) was skipping data keys with 'total' in the name - based on a pattern I was seeing. I think I've found the issue. 

There's a function in compile.py titles has_whiff_of_total which I think is being used to do just that. 

Please could you simply remove this from the programme as it is no longer needed, as we use meta data tags in the dm master to filter out which keys into include in bcompiler - a dm csv file.  

Cheers. Looking forward to our chat later. 

Will.

**Comment by hammerheadlemon** [comment]
Removed function, but untested! You will need to test with your live data. Please upgrade to version 1.13.23 using `pip install -U bcompiler`. Let me know if there are any problems.

**Comment by banillie** [comment]
tested and all good! thanks for sorting so quickly dude.

**Comment by hammerheadlemon** [comment]
Great. Thanks for letting me know. Keep me up to date with any other problems as you enter this crucial period! Raising issues here is best way.... :-)
